### PR TITLE
feat: Add openApp

### PR DESCRIPTION
**Pull request by pnthach95**
I add `openApp?: boolean` to open app when press primitive.
Reason for this feature is, I used `rn-openapp` to open app when `WIDGET_CLICK`, but it didn't work if app was killed.

~~It needs improvement: if you set `openApp` at parent component, then you can't press children. I'm not a pro native developer, I have no idea how to fix it.
Example: CounterWidget, set `openApp` for root component, you can't press `+` or `-`~~ Resolved with v0.3.1

### CODE REVIEW

**Comment by sAleksovski** [comment]
I tried `rn-openapp` and it opens the app even when it is killed.
It just takes a little more time.

I've added `clickAction="OPEN_APP"` to the root `FlexWidget` of `FitnessWidget`, and in `widgetTaskHandler` I added a check:

```ts
if (props.clickAction === 'OPEN_APP') {
  openApp('com.androidwidgetexample');
}
```

I'm attaching a recording:
https://user-images.githubusercontent.com/7473800/229589215-6755ffe4-4063-4fcd-bb65-d17a2081aef2.mp4

I just released `0.3.1` that fixes the issue of nested clickable widgets.
Can you try again?

**Comment by pnthach95** [comment]
v0.3.1 resolved "press any space to open app" case.

[In my case](https://github.com/pnthach95/KarthuriaApp/blob/27362fe0ebe784dbbee28f6a65ce2808e6a00157/src/widgets/event/task.tsx#L79), `rn-openapp` doesn't work, it throws error log:

```
couldn't find DSO to load: libjsc.so
    SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/~~0_yGXoIbID4NdW5P0RSWeA==/vn.pnthach.karthuria-AJmRBMgWka4ztxA5xj8nRw==/lib/arm64 flags = 0]
    SoSource 1: com.facebook.soloader.DirectApkSoSource[root = (/data/app/~~0_yGXoIbID4NdW5P0RSWeA==/vn.pnthach.karthuria-AJmRBMgWka4ztxA5xj8nRw==/base.apk!/lib/arm64-v8a, )]
    SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    Native lib dir: /data/app/~~0_yGXoIbID4NdW5P0RSWeA==/vn.pnthach.karthuria-AJmRBMgWka4ztxA5xj8nRw==/lib/arm64
result: 0

couldn't find DSO to load: libjscexecutor.so caused by: couldn't find DSO to load: libjsc.so
    SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/~~0_yGXoIbID4NdW5P0RSWeA==/vn.pnthach.karthuria-AJmRBMgWka4ztxA5xj8nRw==/lib/arm64 flags = 0]
    SoSource 1: com.facebook.soloader.DirectApkSoSource[root = (/data/app/~~0_yGXoIbID4NdW5P0RSWeA==/vn.pnthach.karthuria-AJmRBMgWka4ztxA5xj8nRw==/base.apk!/lib/arm64-v8a, )]
    SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    Native lib dir: /data/app/~~0_yGXoIbID4NdW5P0RSWeA==/vn.pnthach.karthuria-AJmRBMgWka4ztxA5xj8nRw==/lib/arm64
result: 0 result: 0
```

> I tried rn-openapp and it opens the app even when it is killed.
> It just takes a little more time.

Response time is too long comparing with other apps and my solution.

### Don't merge yet, I'm cooking an idea that can sell you this PR

**Comment by sAleksovski** [comment]
I was trying a few things yesterday, and I got this to work without `openApp` prop.

I'll try to clean that up and release it today.

**Comment by pnthach95** [comment]
I'm trying to pass `clickActionData` to app when open app from widget, which can't do with `rn-openapp`. However, it only work when app is killed, no data when resume from background. I'm stuck.

**Comment by sAleksovski** [comment]
Hi,

Thank you for your effort, and trying multiple things.

Unfortunately, I cannot merge this as is, since it requires multiple modifications to native java files, which will not work out-of-the-box with Expo. It also has the limitation that deep links open only when the app is closed.

I think that the recommended way for handling deep links is to implement something like [Linking](https://reactnative.dev/docs/linking), (or `expo-linking`, or `expo-router`).

I'll close this PR since I just published a [`0.4.0`](https://github.com/sAleksovski/react-native-android-widget/releases/tag/v0.4.0) version that adds `OPEN_APP` and `OPEN_URI` options to `clickAction`. I think it covers your use-case.

You can see the docs [here](https://saleksovski.github.io/react-native-android-widget/docs/handling-clicks), and check out the [commit](https://github.com/sAleksovski/react-native-android-widget/commit/f95fa543837c5cb4a933ae4f1f959bfac0f46ce5) that adds the functionality for examples on how to implement it in your app.

I tried it on a device and opening the app and the deep link is instant.

**Pull request closed without merging**
