### PR TITLE
feat: expose get widget info function

### PR DESCRIPTION
**Pull request by edwinkcw**
I would like to expose the function to getWidgetInfo because I want to start the android service only when a widget is installed. I can use getWidgetInfo to check if my widget is installed

### CODE REVIEW

**Comment by sAleksovski** [comment]
What do you mean by "start the android service only when a widget is installed"?

You can register a [task handler](https://saleksovski.github.io/react-native-android-widget/docs/api/register-widget-task-handler), and it will be called when a widget is added/resized/clicked. The task service does not run continuously.

For updating already added widgets you can use [requestWidgetUpdate](https://saleksovski.github.io/react-native-android-widget/docs/api/request-widget-update). It will check if a widget with that name is added, and call the `renderWidget` callback for each widget. If no widget with that name is added, the callback will not be called.

From application point of view you don't "need" to know if a widget is added or not, just try to update it.

**Comment by edwinkcw** [comment]
because I would like to start a service using [`https://github.com/Rapsssito/react-native-background-actions` ](react-native-background-actions) only when a widget is added. This will show a notification because it utilizes foreground service. I need to check if a widget is added before starting the background job. Otherwise, my app will have a notification occupied even there is no widgets added which confused our user. 

I think I can't rely on the task handler to update my widget. My widget will to be periodically updated.

**Comment by sAleksovski** [comment]
Does something like this work:

```ts
import type { WidgetTaskHandlerProps } from 'react-native-android-widget';
import BackgroundService from 'react-native-background-actions';

export async function widgetTaskHandler(props: WidgetTaskHandlerProps) {
  if (props.widgetAction === 'WIDGET_ADDED') {
    props.renderWidget(<MyWidget />);
    await BackgroundService.start(myWidgetService, options);
  }
}
```

`myWidgetService` will be the service you are using to run the background task and update the widget using `requestWidgetUpdate`.

**Comment by edwinkcw** [comment]
It seems work, but how about when to stop it?

**Comment by sAleksovski** [comment]
I'll decline this PR since I exposed the `getWidgetInfo` in https://github.com/sAleksovski/react-native-android-widget/commit/9739ca880b699243601bd742fa3ca99f005ed49a

New version `0.2.0` is released.

I also added a `widgetNotFound` callback in the `requestWidgetUpdate` function, which can also be used to stop the background task when you try to update the widget, but the widget has been removed.

```ts
requestWidgetUpdate({
  widgetName: 'Counter',
  renderWidget: () => <CounterWidget count={count} />,
  widgetNotFound: () => {
    await BackgroundService.stop();
  }
});
```

**Pull request closed without merging**
